### ISSUE TITLE
LasBasler Camera Configuration Script

### ISSUE THREAD

**Issue by slactjohnson** [pcdshub/pcdsdevices#1128]
## Current Behavior
Cameras are largely configured manually. The cameras do not always come up with the correct settings. 

## Expected Behavior
Cameras should generally come up with the correct settings. 

## Context / environment
The laser group is tired of configuring cameras manually. They want a consistent set of settings for NF/FF cameras in the MODS system. 

## Suggested Solution
Add a default configuration dictionary to NF/FF cameras in the MODS system. The `configure` method provided via the `Device` class can use this dictionary to automatically configure the PVs.

**Comment by ZLLentz** [comment]
Configuration management is not in the scope of the automated test execution framework, though it certainly should be something we solve systematically.

That being said, I don't think we should shy away from simple solutions that we can deploy quickly to solve problems just because there might be a more systematic solution later. I think the suggestion solution here is reasonable.
