### ISSUE TITLE
State Cleanup

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/pcdsdevices#115]
## Expected Behavior

Re-examine how we are doing the `StatesRecord` class. This would be cleaner as a class that we inherit rather than a subcomponent. We should also see how we can generalize this further as to not be require as much re-writing for each specific device class.

**Comment by ZLLentz** [comment]
@teddyrendahl I'm going to tackle this one first because it affects how we design the other device classes.

**Comment by teddyrendahl** [comment]
Was thinking the same thing. Let me know if you need assistance @ZLLentz

**Comment by ZLLentz** [comment]
I'm going to sum up my ideas here before diving in. Let me know what you think so we can be on the same page. The goal is to get to a point where we can write code like:

```
from enum import Enum

from pcdsdevices.states import StatesDevice


class PIM(StatesDevice):
    _states_enum = Enum('PIMStates', 'DIODE YAG OUT')


my_pim = PIM('HX2:SB1:PIM')
``` 

And then we have the following features for free:
- `my_pim.state` is an `EpicsSignal` for the state value and setter
- `my_pim.state_config` is a `Device` subclass with all the state position, delta information


So we avoid the awful `my_pim.states.state` constructs but can still change offset/delta from Python, and it is straightforward to create these devices by subclassing `StatesDevice` and providing an Enum. The implementation isn't too bad because we always know which components we need and their names, and only what the `state_config` component is may change.

Some questions:
- Is separating a `Signal` and a connected configuration `Device` a sustainable design choice?
- Do we need to support multiple states in one `Device`?
- Is this a sufficient feature set, or do we want to have things like `my_pim.state_motor` as well?
- Can this be (should this be) constructed in a such a way to include the generic PVState functionality too? We can look for a key like `_states_pvs={}` for example.

**Comment by ZLLentz** [comment]
I suppose we also then have `StatesDevice` provide overrides for `set` and `position`. Might have also missed other things.

**Comment by teddyrendahl** [comment]
I really like the implementation goal above. Still trying to process what the proper division of sub-devices should look like. Also absolutely think that StatesDevice should reimplement `set` and `position`

**Comment by ZLLentz** [comment]
I'm going to get started and defer to doing the sub-device division later, but sticking with a single `state` signal for now. I agree that this part is less obvious without more thought.

**Comment by ZLLentz** [comment]
Leaving this open with the following goals:

1. Generalize insert/remove for in/out devices. This generalization should work for all states devices, regardless of whether they are pv states or states record. (handle when we clean up `inout.py`)
2. Add the states config for the states record devices. (handle in a separate PR)

Any others?
