### ISSUE TITLE
TprTrigger _get_delay Calculation appears incorrect

### ISSUE THREAD

**Issue by slactjohnson** [pcdshub/pcdsdevices#1302]
## Current Behavior
There seems to be a discrepancy in how the `TprTrigger.ns_delay` readback calculation is done compared to the setpoint. The setpoint appears to be calculated correctly, but the `ns_delay.get()` method is off by about 12 nanoseconds (99790 setpoint vs 99778 readback), which is huge. The ticks + taps conversion, done manually, matches the setpoint, so the issue seems to be with the readback calculation. See screenshots below. 

![image](https://github.com/user-attachments/assets/0357ecec-55cd-4696-8452-32b28f1a0efa)

![image](https://github.com/user-attachments/assets/b435cca8-dac0-4928-a848-da3d804e85b4)

![image](https://github.com/user-attachments/assets/a7eda184-0b63-44ac-8876-4f5202879e55)

## Expected Behavior
`The setpoint and readback should be much closer to each other, typically within 400ps or less. 

## Context / environment
I was working up a quick script for a test and noticed this looked off.

**Comment by slactjohnson** [comment]
The `TprMotor` class also appears to be incorrect: 

![image](https://github.com/user-attachments/assets/a4192e27-3ead-41ef-9416-c599a022c707)

**Comment by KaushikMalapati** [comment]
@slactjohnson, I think this is entirely caused by TPR_TICK_NS being set to 5.384 instead of 1/0.185714.
 
EX
18532 * 5.384            + 28 * 0.08 = 99,778.528
18532 * (1/0.185714) + 28 * 0.08 = 99,790.0858274551

TprTrigger and TprMotor both use the TPR_TICK_NS constant. Out of curiosity where is the exact value for length of a tick defined?
