### ISSUE TITLE
lxt_ttc

### ISSUE THREAD

**Issue by ZryletTC** [pcdshub/pcdsdevices#535]
This motor moves both lxt and txt (I think?). See old python for more info

**Comment by klauer** [comment]
Taking a look now. If anyone else jumped on this in the mean time, let me konw.

**Comment by klauer** [comment]
A simple 6 character motor name hides behind it a _lot_ of functionality. Exploring the beamline codebase:

* Time stage series compensation using stages `lxt` and `txt` (appears to be like a `SyncAxes`-style thing)
* `lxt` is already implemented as the `LaserTiming` class, a virtual motor based on vitara positions
* `txt` is a virtual motor based on `xcsTTdelay`, which uses delay stage to time (perhaps could use `DelayBase`) to convert the `tt_delay` stage position
* `tt_delay` is a motor with pv name `XCS:LAS:MMN:01`, record type `xps8p` (I think this is PCDS's `motor`-record compatible-ish XPS motor record)

More in a bit...

**Comment by ZLLentz** [comment]
Yes, my recollection is that this is a sync-axes-like thing that moves two stages at the same time to adjust one timing but not another- my memory is hazy beyond that.

**Comment by silkenelson** [comment]
Yes: this stage moves lxt (the viatara/laser) and the also ttc (stage that moves the time tool signal to keep) to compensate so that we can get the true laser-xray delay by using the lxt-value and the result of the analysis of the time tool data and we don't count anything double.
ttc has a smaller range, so lxt_ttc will move both when it can and when ttc is out of range, it will only move lxt until we are back in the range where ttc can move.

**Comment by klauer** [comment]
Thanks for the additional context. 

(And separately - sorry, this one's taking me a bit longer than I expected - hope to finish this tomorrow.)
