### ISSUE TITLE
Idea: OrphanerDevice (for large, system-level device hierarchies)

### ISSUE THREAD

**Issue by klauer** [pcdshub/pcdsdevices#617]
Large hierarchies of devices can be convenient to design, but cause problems when scanning.

ophyd (really bluesky) make the broad assumption that *all* devices in a hierarchy must be functioning to properly stage any device in the tree. This is erring on the side of caution and overall makes sense.

The split and delay system may be the largest example we have (?): https://github.com/pcdshub/hxrsnd/blob/9b05312df491903ec9cc9e7bc14a11b7c4984112/hxrsnd/sndsystem.py#L20

At the top level, all devices are related mainly as a convenient grouping into a "system" - but if a camera is failing to stage in a distant relative's tree, scanning a leaf-node motor should not be an issue as it is currently.

"OrphanerDevice"
-------------------

```python
class System(OrphanerDevice):
    subsystem1 = Cpt(...)
    subsystem2 = Cpt(...)
    subsystem3 = Cpt(...)

system = System()
RE(scan([system.subsystem1], ...))   # only stages subsystem1 and below

# It could do this by effectively orphaning its children at init time:
assert system.subsystem1.parent is None  # no going back up the hierarchy, sorry

# system.stage() -> RuntimeError
```

This allows you to still group the system together using the convenient component notation, scan unrelated subsystems, and so on.

I'm sure there are downsides I'm not thinking of here, but throwing it out there for now.

**Comment by ZLLentz** [comment]
I like the idea

**Comment by klauer** [comment]
We could probably support this on any general `Cpt` or device that inherits from `BaseInterface` as well with more granularity. Either with variety metadata or some other flag we recognize.

**Comment by ZLLentz** [comment]
Having a shared class for this also lets us design a specific typhos template for "devices with many subdevices"

**Comment by klauer** [comment]
The shared class is very compelling for typhos - good point!

**Comment by ZLLentz** [comment]
I'm starting work on this right now as a stepping stone to the CCM edits that Diling asked for. I have two thoughts:
1. I'd like to call this `GroupDevice` instead of `OrphanerDevice` because it sounds more friendly and won't be misread as `OphydDevice`
2. I think there's no reason to change the behavior of `stage` at all- what if someone does want to stage everything? Seems like the only thing needed for now is the post-init strip of the parent references. I can be convinced otherwise very easily if you disagree.

**Comment by klauer** [comment]
Good call on the name. 😁 

For (2), I think the only issue is if someone tries to stage "system" and "system.subsystem{1,2,3}" in the same run, since bluesky can't figure out the relationship between the devices. Either this small thing was part of the "RuntimeError" note I noted above, or it was part of the "downsides I'm not thinking of"... 🤷‍♂️ not that it really matters at this point, I suppose!

**Comment by ZLLentz** [comment]
Oh that's a really good point, we still have the redundant staging error as a possibility!
I'll make stage/unstage runtime errors as suggested so we get a clear error

**Comment by dlzhu** [comment]
Decouple a bit more the motor being scanned to the 'object' makes a lot of sense. On the other hand, I feel this relates to the hierachy of objects that very often confuses me. For example, having alio under ccm.calc instead of just under ccm, while chi2 and some other motors are directly under ccm. I would prefer to always have the option to 'scan an individual motor' ignoring what it belongs to, and in a fraction of cases, the same motor can be 'scanned' as a compenent of an object, in which case a few more checks are done. Can elaborate more later.

I think I'm still not familiar with this whole concept of 'stage/unstage'. My first impression is that the subsystem layer adds 'complexity' in terms of both building the device and extra argument needed for doing a scan. We might be able to hide that with a wrapper, hence another layer. Would be happy to try it out though since I could have misunderstood.

**Comment by ZLLentz** [comment]
I think for the CCM in particular we can do better in multiple ways, and this orphaner/group device idea is just one of them. It's being hit first because it should help many different devices.

The intent of the hierarchy in CCM was to reduce complexity on the dev side by splitting up the various features into different subclasses. This gets a bit messy with the calculation due to the way `PseudoPositioner` works in `ophyd`- essentially, I was forced to quarantine the calculation to a subdevice or else the top-level CCM object would be less stable. To facilitate that, I also dropped the alio motor needed for the calculation down to the subdevice.

With more knowledge/ideas now this can be done slightly better, and where it cannot be done better it can at least be aliased.
